services:
  - type: web
    name: dashboard-ventas
    env: python
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app.server --bind 0.0.0.0:10000
    plan: starter